permalink   : /:categories/:year/:title/
markdown    : kramdown
highlighter : pygments

paginate: 2 #6
comments: true
paginate_path: "/page/:num"

source: source
destination: _site
sass:
  sass_dir: _scss
  style: compressed

cover: /assets/images/default-cover.png

# site title, description, meta_description, meta_keywords
# Details for the RSS feed generator
name: the_cynical_dba
title: the_cynical_dba
description: "SQL and other things"
keywords: "DBA, SQL, Blog, MSSQL, Databases"
url: http://thecynicaldba.com
baseurl: ""
domain_name: thecynicaldba.com
google_analytics: UA-102162987-1
repo: https://github.com/JosiahSiegel/the-cynical-dba.git
disqus_shortname: "cynical-dba"

author:
  name      : Josiah Siegel
  image     : /assets/images/author.jpg
  email     : josiah0601@gmail.com
  url       : http://thecynicaldba.com
  facebook  : 
  twitter   : 
  instagram : 
  github    : https://github.com/JosiahSiegel
  linkedin  : https://www.linkedin.com/in/josiah-siegel-62b52b24/
  bio       : ""

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
